version: "3.4"
services:
  todo-client:
    build:
      context: client/gopath/src
      target: builder
    environment:
      TODO_TESTSERVER: todo-server
    command:
      - /bin/bash
      - -e
      - -c
      - |
        # todo-serverの起動待ち
        sleep 20
        # テストの実行
        go test -v ./...
        echo $TODO_TESTSERVER
        echo `date +"%Y/%m/%d %H:%M:%S"`" 生成したバイナリからpingサブコマンドを実行します。"
        ./todo ping --host todo-server --protocol http --port 8000
        echo `date +"%Y/%m/%d %H:%M:%S"`" 生成したバイナリからloginサブコマンドを実行します。"
        ./todo login --username test_user --password test_password --host todo-server --protocol http --port 8000
        echo `date +"%Y/%m/%d %H:%M:%S"`" 生成したバイナリからcreateサブコマンドを実行します。"
        ./todo create --title "todo" --description "todo-description"
        echo `date +"%Y/%m/%d %H:%M:%S"`" 生成したバイナリからgetサブコマンドを実行します。(全タスク取得)"
        ./todo get
        echo `date +"%Y/%m/%d %H:%M:%S"`" 生成したバイナリからgetサブコマンドを実行します。(単一タスク取得)"
        ./todo get --id `./todo create --title "todoGet" --description "Get"| grep "ID" | sed -e 's/ID: //'`
        echo `date +"%Y/%m/%d %H:%M:%S"`" 生成したバイナリからdeleteサブコマンドを実行します。"
        ./todo delete --id `./todo create --title "todoGet" --description "Get"| grep "ID" | sed -e 's/ID: //'`
        echo `date +"%Y/%m/%d %H:%M:%S"`" 生成したバイナリからupdateサブコマンドを実行します。"
        ./todo update --id `./todo create --title "todoGet" --description "Get"| grep "ID" | sed -e 's/ID: //'` --title "updated" --description "updated description" --status "RUNNING"
