version: "3.4"
services:
  todo-server:
    build:
      context: server/
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: sampleapp
      MYSQL_HOST: todo-mysql
    command:
      - /bin/sh
      - -e
      - -c
      - |
        sleep 5
        python manage.py migrate
        python manage.py loaddata sampleapp/fixtures/test_user
        python manage.py loaddata task_status #追加
        gunicorn -w 2 -b 0.0.0.0:8000 sampleapp.wsgi
  todo-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: sampleapp
    expose:
      - 3306
